build: off

branches:
  only:
    - master

environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"
  - nodejs_version: "8"

skip_tags: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run unit-tests
